# File: docker-compose.yml (Nằm ở thư mục gốc)
# Đây là file tổng, nó sẽ tự động chọn file con để chạy dựa trên biến ${APP_ENV}

version: "3.8"

name: social-network-${APP_ENV:-dev} # Tên project sẽ là social-network-dev hoặc pro

include:
  # Trỏ tới file cấu hình tương ứng. Mặc định là 'dev' nếu không set APP_ENV
  - path:
      - docker/${APP_ENV:-dev}/docker-compose.yml